[illumio]
fqdn = "jds-vspshere3.poc.segmentationpov.com"
port = 8443 # Integer (no quotes).
org = 1 # Integer (no quotes). Value is 1 for on-prem PCE installations.
user = "api_16f3a187a6c3bde44"
key = "48667baa2c2ac2a95e3d76c5b4ced658c177d175062766c263b8dd71d60949da"
match_field = "host_name" # Matches to ServniceNow match_field. Must either be "host_name" or "name".

[parser]
parserfile = parser-table.csv
samplehosts = hostname.csv